name: guyc_at
description: A server app using the shelf package.
version: 1.0.0
repository: https://github.com/gchait/guyc-at

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
