FROM alpine:3.20

RUN apk --no-cache upgrade \
    && apk --no-cache add postgresql15-client

WORKDIR /app

COPY create_user_database.sql ./
COPY create_user_database.sh ./

CMD ["./create_user_database.sh"]
