services:
  backend:
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mariadb
  
  mariadb:
    image: mariadb:11.0.2-jammy
    ports:
      - ${MARIA_PORT}:${MARIA_PORT}
    environment:
      - MARIADB_TCP_PORT=${MARIA_PORT}
      - MARIADB_DATABASE=${MARIA_DB}
      - MARIADB_USER=${MARIA_USER}
      - MARIADB_PASSWORD=${MARIA_PASS}
      - MARIADB_ROOT_PASSWORD=${MARIA_ROOTPASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -h localhost -u root -p "$${MARIADB_ROOT_PASSWORD}"
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mariadb_data:
