FROM python:3.11-slim-bookworm

EXPOSE ${PORT}
WORKDIR /tmp

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc libmariadb-dev pkg-config \
    && apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/*

COPY ./reqs.txt .
RUN pip install --no-cache-dir -r ./reqs.txt \
    && rm ./reqs.txt

WORKDIR /app
COPY src/ .
COPY .env ./

CMD ./run.sh
