Vagrant.configure("2") do |config|
  config.vm.box = "bento/fedora-38"
  config.vm.post_up_message = ""
  
  config.vm.disk :disk, size: "#{ENV['DISK_GB']}GB", primary: true

  config.vm.provider :virtualbox do |v|
    v.memory = ENV["MEMORY"]
    v.cpus = ENV["CPUS"]
  end
  
  config.vm.network :forwarded_port,
    guest: ENV["PORT_TCP"],
    host: ENV["PORT_TCP"],
    auto_correct: true
    
  config.vm.provision :shell, path: "bootstrap.sh", args: "vagrant"
  
  config.vm.provision :shell, inline: <<~ROOT
    su vagrant <<-VAGRANT
      git config --global user.name "#{ENV['GIT_NAME']}"
      git config --global user.email "#{ENV['GIT_EMAIL']}"
    VAGRANT
  ROOT
end
