---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-deleter
  namespace: XXX

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-deleter-cr
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "delete"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-deleter-crb
subjects:
  - kind: ServiceAccount
    name: pod-deleter
    namespace: XXX
roleRef:
  kind: ClusterRole
  name: pod-deleter-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: XXX
  name: failed-pod-cleanup
spec:
  schedule: "*/XXX * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: XXX
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: pod-deleter
          containers:
            - name: kubectl-pod-cleanup
              image: xxx/kubectl:XXX
              command:
                - "sh"
                - "-c"
                - "kubectl delete -A --field-selector 'status.phase=Failed' pods"
