---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xx

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xx
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "watch", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xx
subjects:
- kind: ServiceAccount
  name: xx
  apiGroup: ""
roleRef:
  kind: Role
  name: xx
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: xx
  annotations:
    kubernetes.io/service-account.name: xx

---
apiVersion: secretsmanager.aws.crossplane.io/v1beta1
kind: Secret
metadata:
  name: "{{ .Release.Namespace }}-xx-kubeconfig"
spec:
  forProvider:
    region: {{ .Values.region }}
    forceDeleteWithoutRecovery: true
    stringSecretRef:
      name: xx
      namespace: {{ .Release.Namespace }}
