---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: XXX
  annotations:
    pod-policies.kyverno.io/autogen-controllers: Job,Deployment,StatefulSet
    policies.kyverno.io/description: >-
      XXX
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: XXX
      preconditions:
        any:
          - key: "{{`{{ to_string(request.object.metadata.ownerReferences[?kind=='DaemonSet']) }}`}}"
            operator: AnyIn
            value:
              - "null"
              - "[]"
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces: XXX
          - resources:
              selector:
                matchLabels:
                  FARGATE: XXX
      mutate:
        patchStrategicMerge:
          spec:
            nodeSelector:
              xxx: yyy
