FROM python:3.11-slim-bookworm

WORKDIR /tmp
COPY ./reqs.txt .

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc libmariadb-dev pkg-config \
    && pip install --no-cache-dir -r ./reqs.txt \
    && apt-get purge -y --auto-remove gcc libmariadb-dev pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* ./reqs.txt

WORKDIR /app
COPY src/ .
COPY .env ./

CMD ["./run.sh"]
